#!/usr/bin/env bash
set -euo pipefail

ARCHIVE_NAME="${ARCHIVE_NAME:-ai-scientist-mcts-src.tgz}"
CONFIG="${CONFIG:-bfts_config.yaml}"
IDEA_IDX="${IDEA_IDX:-0}"
RESULTS_DIR="${RESULTS_DIR:-results}"

VM_NAME="${VM_NAME:-gce-shu2}"
ZONE="${ZONE:-asia-southeast1-c}"
PROJECT="${PROJECT:-gcp-samples-ic0}"
REMOTE_DIR="${REMOTE_DIR:-~}"

DETACH="${DETACH:-1}"
FETCH_ONLY="${FETCH_ONLY:-0}"
ATTEMPT_ID="${ATTEMPT_ID:-0}"
SESSION_NAME="${SESSION_NAME:-ai_scientist_${ATTEMPT_ID}}"

# This repository currently uses mcts_discovery.json and mcts_discovery.py.
# --load_code expects a Python seed file with the same basename as --load_ideas.
IDEA_JSON="${IDEA_JSON:-ai_scientist/ideas/mcts_discovery.json}"
SEED_CODE="${SEED_CODE:-${IDEA_JSON%.json}.py}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${PROJECT_DIR:-$(basename "${SCRIPT_DIR}")}"
LOCAL_PARENT_DIR="$(dirname "${SCRIPT_DIR}")"
cd "${LOCAL_PARENT_DIR}"

find_gcloud() {
  if command -v gcloud >/dev/null 2>&1; then
    command -v gcloud
  elif [[ -x "${HOME}/google-cloud-sdk/bin/gcloud" ]]; then
    printf '%s\n' "${HOME}/google-cloud-sdk/bin/gcloud"
  else
    printf 'Error: gcloud not found in PATH or %s/google-cloud-sdk/bin/gcloud\n' "${HOME}" >&2
    exit 1
  fi
}

GCLOUD="$(find_gcloud)"

run_gcloud_ssh() {
  "${GCLOUD}" compute ssh "${VM_NAME}" \
    --zone "${ZONE}" \
    --project "${PROJECT}" \
    "$@"
}

run_gcloud_scp() {
  "${GCLOUD}" compute scp "$@" \
    --zone "${ZONE}" \
    --project "${PROJECT}"
}

shell_quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\''/g")"
}

fetch_results() {
  mkdir -p "${RESULTS_DIR}"
  local remote_archive="${REMOTE_DIR}/ai-scientist-result-${ATTEMPT_ID}.tgz"
  local local_archive="${RESULTS_DIR}/ai-scientist-result-${ATTEMPT_ID}.tgz"

  printf 'Downloading result archive from %s:%s\n' "${VM_NAME}" "${remote_archive}"
  run_gcloud_scp "${VM_NAME}:${remote_archive}" "${local_archive}"

  printf 'Extracting result archive into %s\n' "${RESULTS_DIR}"
  tar -xzf "${local_archive}" -C "${RESULTS_DIR}"
  printf 'Done. Local results are under: %s\n' "${RESULTS_DIR}"
}

if [[ "${FETCH_ONLY}" == "1" ]]; then
  fetch_results
  exit 0
fi

if [[ ! -d "${PROJECT_DIR}" ]]; then
  printf 'Error: project directory not found: %s\n' "${PROJECT_DIR}" >&2
  printf 'Run this script from the parent directory that contains %s.\n' "${PROJECT_DIR}" >&2
  exit 1
fi

if [[ ! -f "${PROJECT_DIR}/${CONFIG}" ]]; then
  printf 'Error: config file not found: %s/%s\n' "${PROJECT_DIR}" "${CONFIG}" >&2
  exit 1
fi

if [[ ! -f "${PROJECT_DIR}/${IDEA_JSON}" ]]; then
  printf 'Error: idea JSON not found: %s/%s\n' "${PROJECT_DIR}" "${IDEA_JSON}" >&2
  exit 1
fi

if [[ ! -f "${PROJECT_DIR}/${SEED_CODE}" ]]; then
  printf 'Error: seed code not found: %s/%s\n' "${PROJECT_DIR}" "${SEED_CODE}" >&2
  printf 'The --load_code launch path requires the seed code basename to match the idea JSON basename.\n' >&2
  exit 1
fi

printf 'Creating source archive: %s\n' "${ARCHIVE_NAME}"
rm -f "${ARCHIVE_NAME}"
COPYFILE_DISABLE=1 tar -czf "${ARCHIVE_NAME}" \
  --exclude="${PROJECT_DIR}/.git" \
  --exclude="${PROJECT_DIR}/.venv" \
  --exclude="${PROJECT_DIR}/logs" \
  --exclude="${PROJECT_DIR}/workspaces" \
  --exclude="${PROJECT_DIR}/experiments" \
  --exclude="${PROJECT_DIR}/data" \
  --exclude="${PROJECT_DIR}/.matplotlib-cache" \
  --exclude="${PROJECT_DIR}/${RESULTS_DIR}" \
  --exclude="${ARCHIVE_NAME}" \
  --exclude='*/__pycache__' \
  --exclude='*/.DS_Store' \
  --exclude='._*' \
  --exclude='*/._*' \
  "${PROJECT_DIR}"

printf 'Uploading source archive to VM\n'
run_gcloud_scp "${ARCHIVE_NAME}" "${VM_NAME}:${REMOTE_DIR}/${ARCHIVE_NAME}"

if [[ -n "${OPENAI_API_KEY:-}" || -n "${S2_API_KEY:-}" ]]; then
  tmp_env="$(mktemp)"
  {
    printf '# Generated by upload_to_vm.sh for AI Scientist MCTS run\n'
    if [[ -n "${OPENAI_API_KEY:-}" ]]; then
      printf 'export OPENAI_API_KEY=%s\n' "$(shell_quote "${OPENAI_API_KEY}")"
    fi
    if [[ -n "${S2_API_KEY:-}" ]]; then
      printf 'export S2_API_KEY=%s\n' "$(shell_quote "${S2_API_KEY}")"
    fi
  } > "${tmp_env}"

  remote_env_tmp="${REMOTE_DIR}/.ai_scientist_env.upload.${ATTEMPT_ID}"
  printf 'Uploading ~/.ai_scientist_env to VM from local environment variables\n'
  run_gcloud_scp "${tmp_env}" "${VM_NAME}:${remote_env_tmp}"
  rm -f "${tmp_env}"
  run_gcloud_ssh --command "set -euo pipefail; mv ${remote_env_tmp} \${HOME}/.ai_scientist_env; chmod 600 \${HOME}/.ai_scientist_env"
else
  printf 'No local OPENAI_API_KEY or S2_API_KEY found; leaving VM ~/.ai_scientist_env unchanged.\n'
fi

remote_runner="$(mktemp)"
cat > "${remote_runner}" <<REMOTE_EOF
#!/usr/bin/env bash
set -euo pipefail

ARCHIVE_NAME=$(shell_quote "${ARCHIVE_NAME}")
CONFIG=$(shell_quote "${CONFIG}")
IDEA_IDX=$(shell_quote "${IDEA_IDX}")
PROJECT_DIR=$(shell_quote "${PROJECT_DIR}")
REMOTE_DIR=$(shell_quote "${REMOTE_DIR}")
ATTEMPT_ID=$(shell_quote "${ATTEMPT_ID}")
IDEA_JSON=$(shell_quote "${IDEA_JSON}")
SEED_CODE=$(shell_quote "${SEED_CODE}")
RESULT_ARCHIVE="\${HOME}/ai-scientist-result-\${ATTEMPT_ID}.tgz"
LAST_EXPERIMENT_FILE="\${HOME}/ai_scientist_last_experiment.txt"

REMOTE_DIR_EXPANDED="\${REMOTE_DIR/#\~/\${HOME}}"
REMOTE_PROJECT_DIR="\${REMOTE_DIR_EXPANDED}/\${PROJECT_DIR}"

archive_latest_result() {
  set +e
  if [[ ! -d "\${REMOTE_PROJECT_DIR}/experiments" ]]; then
    echo "No experiments directory found to archive."
    return 0
  fi

  latest="\$(find "\${REMOTE_PROJECT_DIR}/experiments" -mindepth 1 -maxdepth 1 -type d -print 2>/dev/null | sort | tail -n 1)"
  if [[ -z "\${latest}" ]]; then
    echo "No experiment result directories found."
    return 0
  fi

  echo "\${latest}" > "\${LAST_EXPERIMENT_FILE}"
  tar -czf "\${RESULT_ARCHIVE}" -C "\$(dirname "\${latest}")" "\$(basename "\${latest}")"
  echo "Archived latest experiment: \${latest}"
  ls -lh "\${RESULT_ARCHIVE}"
  return 0
}

on_exit() {
  status="\$?"
  echo "Remote run exiting with status \${status}; attempting to archive latest result."
  archive_latest_result || true
}
trap on_exit EXIT

mkdir -p "\${REMOTE_DIR_EXPANDED}"
cd "\${REMOTE_DIR_EXPANDED}"

venv_stash="\${PROJECT_DIR}.venv.stash.\${ATTEMPT_ID}"
if [[ -d "\${PROJECT_DIR}/.venv" ]]; then
  rm -rf "\${venv_stash}"
  mv "\${PROJECT_DIR}/.venv" "\${venv_stash}"
fi

rm -rf "\${PROJECT_DIR}"
tar -xzf "\${ARCHIVE_NAME}" -C "\${REMOTE_DIR_EXPANDED}"

if [[ -d "\${venv_stash}" ]]; then
  mv "\${venv_stash}" "\${PROJECT_DIR}/.venv"
fi

cd "\${REMOTE_PROJECT_DIR}"

if [[ ! -d .venv ]]; then
  python3 -m venv .venv
fi

.venv/bin/python -m pip install --upgrade pip
.venv/bin/pip install -r requirements.txt
.venv/bin/pip install psutil

if [[ -f "\${HOME}/.ai_scientist_env" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "\${HOME}/.ai_scientist_env"
  set +a
fi

if [[ -z "\${OPENAI_API_KEY:-}" ]]; then
  echo "Error: OPENAI_API_KEY is not set on the VM. Set it in ~/.ai_scientist_env or export it locally before upload."
  exit 1
fi

if [[ ! -f "\${IDEA_JSON}" ]]; then
  echo "Error: idea JSON not found on VM: \${IDEA_JSON}"
  exit 1
fi

if [[ ! -f "\${SEED_CODE}" ]]; then
  echo "Error: seed code not found on VM: \${SEED_CODE}"
  exit 1
fi

compile_files=(
  "ai_scientist/llm.py"
  "ai_scientist/vlm.py"
  "ai_scientist/treesearch/agent_manager.py"
  "ai_scientist/treesearch/parallel_agent.py"
  "ai_scientist/treesearch/log_summarization.py"
  "launch_scientist_bfts.py"
  "\${SEED_CODE}"
)

for f in "\${compile_files[@]}"; do
  if [[ ! -f "\${f}" ]]; then
    echo "Error: py_compile target missing: \${f}"
    exit 1
  fi
  .venv/bin/python -m py_compile "\${f}"
done

launch_args=(
  "launch_scientist_bfts.py"
  "--load_ideas" "\${IDEA_JSON}"
  "--idea_idx" "\${IDEA_IDX}"
  "--attempt_id" "\${ATTEMPT_ID}"
  "--load_code"
)

if grep -q -- '"--config"' launch_scientist_bfts.py; then
  launch_args+=("--config" "\${CONFIG}")
else
  if [[ "\${CONFIG}" != "bfts_config.yaml" ]]; then
    echo "Error: launch_scientist_bfts.py does not support --config, but CONFIG=\${CONFIG}."
    exit 1
  fi
  echo "launch_scientist_bfts.py has no --config flag; using repository bfts_config.yaml."
fi

.venv/bin/python -u "\${launch_args[@]}"
REMOTE_EOF

remote_runner_path="${REMOTE_DIR}/ai-scientist-remote-run-${ATTEMPT_ID}.sh"
run_gcloud_scp "${remote_runner}" "${VM_NAME}:${remote_runner_path}"
rm -f "${remote_runner}"
run_gcloud_ssh --command "chmod +x ${remote_runner_path}"

if [[ "${DETACH}" == "1" ]]; then
  printf 'Ensuring tmux and PDF utilities are installed on VM\n'
  run_gcloud_ssh --command "command -v tmux >/dev/null 2>&1 && command -v pdftotext >/dev/null 2>&1 || (sudo apt-get update && sudo apt-get install -y tmux poppler-utils)"

  log_file="\${HOME}/ai-scientist-run-${ATTEMPT_ID}.log"
  remote_cmd="set -euo pipefail; if tmux has-session -t ${SESSION_NAME} 2>/dev/null; then echo 'tmux session already exists: ${SESSION_NAME}' >&2; exit 1; fi; tmux new-session -d -s ${SESSION_NAME} \"bash ${remote_runner_path} > ${log_file} 2>&1\"; echo 'Started tmux session: ${SESSION_NAME}'; echo 'Log file: ${log_file}'"
  run_gcloud_ssh --command "${remote_cmd}"

  cat <<MSG

Detached run started on ${VM_NAME} in tmux session ${SESSION_NAME}.

Follow log:
  ${GCLOUD} compute ssh ${VM_NAME} --zone ${ZONE} --project ${PROJECT} --command "tail -f ~/ai-scientist-run-${ATTEMPT_ID}.log"

Attach tmux:
  ${GCLOUD} compute ssh ${VM_NAME} --zone ${ZONE} --project ${PROJECT} --command "tmux attach -t ${SESSION_NAME}"

Fetch result after completion:
  FETCH_ONLY=1 ATTEMPT_ID=${ATTEMPT_ID} ./upload_to_vm.sh

MSG
else
  run_gcloud_ssh --command "bash ${remote_runner_path}"
  fetch_results
fi
